/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => RememberScrollPositionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  restoreCursor: true,
  maxPositions: 500,
  persistToDisk: true,
  filePath: "",
  restoreDelay: 50,
  respectLinks: true
};

// src/store.ts
var import_obsidian = require("obsidian");
function getDeviceId() {
  const key = "remember-scroll-position-device-id";
  let id = window.localStorage.getItem(key);
  if (!id) {
    const arr = new Uint8Array(4);
    crypto.getRandomValues(arr);
    id = Array.from(arr, (b) => b.toString(16).padStart(2, "0")).join("");
    window.localStorage.setItem(key, id);
  }
  return id;
}
var _PositionStore = class _PositionStore {
  constructor(plugin, settings) {
    this.positions = {};
    this.dirty = false;
    this.writeTimer = null;
    this.plugin = plugin;
    this.settings = settings;
    this.deviceId = getDeviceId();
  }
  /**
   * Get the device-specific file path for positions storage.
   * Replaces "positions.json" with "positions-{deviceId}.json" in the configured path.
   */
  getFilePath() {
    const base = this.settings.filePath;
    return base.replace(/positions\.json$/, `positions-${this.deviceId}.json`);
  }
  /**
   * Load positions from disk if persistence is enabled.
   */
  async load() {
    if (!this.settings.persistToDisk) return;
    const filePath = (0, import_obsidian.normalizePath)(this.getFilePath());
    try {
      if (await this.plugin.app.vault.adapter.exists(filePath)) {
        const data = await this.plugin.app.vault.adapter.read(filePath);
        if (data) {
          this.positions = JSON.parse(data);
        }
      } else {
        const oldPath = (0, import_obsidian.normalizePath)(this.settings.filePath);
        if (await this.plugin.app.vault.adapter.exists(oldPath)) {
          const data = await this.plugin.app.vault.adapter.read(oldPath);
          if (data) {
            this.positions = JSON.parse(data);
            this.dirty = true;
            await this.writeToDisk();
          }
        }
      }
    } catch (e) {
      console.error("Remember Scroll Position: failed to load positions file:", e);
      this.positions = {};
    }
  }
  /**
   * Get the saved position for a file key.
   */
  get(key) {
    return this.positions[key];
  }
  /**
   * Save a position for a file key.
   */
  set(key, position) {
    this.positions[key] = position;
    this.dirty = true;
    this.evict();
    this.scheduleDiskWrite();
  }
  /**
   * Remove a position by key.
   */
  delete(key) {
    if (key in this.positions) {
      delete this.positions[key];
      this.dirty = true;
      this.scheduleDiskWrite();
    }
  }
  /**
   * Rename a key (for file renames).
   */
  rename(oldKey, newKey) {
    if (oldKey in this.positions) {
      this.positions[newKey] = this.positions[oldKey];
      delete this.positions[oldKey];
      this.dirty = true;
      this.scheduleDiskWrite();
    }
  }
  /**
   * Get the number of stored positions.
   */
  get size() {
    return Object.keys(this.positions).length;
  }
  /**
   * Flush any pending writes to disk. Call on plugin unload.
   */
  async flush() {
    if (this.writeTimer !== null) {
      window.clearTimeout(this.writeTimer);
      this.writeTimer = null;
    }
    if (this.dirty) {
      await this.writeToDisk();
    }
  }
  /**
   * Evict oldest entries if over the limit.
   */
  evict() {
    if (this.settings.maxPositions <= 0) return;
    const keys = Object.keys(this.positions);
    if (keys.length <= this.settings.maxPositions) return;
    const sorted = keys.sort(
      (a, b) => {
        var _a, _b;
        return ((_a = this.positions[a].timestamp) != null ? _a : 0) - ((_b = this.positions[b].timestamp) != null ? _b : 0);
      }
    );
    const toRemove = sorted.length - this.settings.maxPositions;
    for (let i = 0; i < toRemove; i++) {
      delete this.positions[sorted[i]];
    }
  }
  /**
   * Schedule a debounced write to disk.
   */
  scheduleDiskWrite() {
    if (!this.settings.persistToDisk || this.writeTimer !== null) return;
    this.writeTimer = window.setTimeout(() => {
      this.writeTimer = null;
      if (this.dirty) {
        void this.writeToDisk();
      }
    }, _PositionStore.WRITE_DEBOUNCE);
  }
  /**
   * Write positions to disk.
   */
  async writeToDisk() {
    if (!this.settings.persistToDisk) return;
    const filePath = (0, import_obsidian.normalizePath)(this.getFilePath());
    try {
      const dir = filePath.substring(0, filePath.lastIndexOf("/"));
      if (dir && !await this.plugin.app.vault.adapter.exists(dir)) {
        await this.plugin.app.vault.adapter.mkdir(dir);
      }
      const data = JSON.stringify(this.positions);
      await this.plugin.app.vault.adapter.write(filePath, data);
      this.dirty = false;
    } catch (e) {
      console.error("Remember Scroll Position: failed to write positions file:", e);
    }
  }
};
/** Debounce interval for writing to disk (ms) */
_PositionStore.WRITE_DEBOUNCE = 2e3;
var PositionStore = _PositionStore;

// src/tracker.ts
var import_obsidian2 = require("obsidian");

// node_modules/monkey-around/dist/index.mjs
function around(obj, factories) {
  const removers = Object.keys(factories).map((key) => around1(obj, key, factories[key]));
  return removers.length === 1 ? removers[0] : function() {
    removers.forEach((r) => r());
  };
}
function around1(obj, method, createWrapper) {
  const inherited = obj[method], hadOwn = obj.hasOwnProperty(method), original = hadOwn ? inherited : function() {
    return Object.getPrototypeOf(obj)[method].apply(this, arguments);
  };
  let current = createWrapper(original);
  if (inherited)
    Object.setPrototypeOf(current, inherited);
  Object.setPrototypeOf(wrapper, current);
  obj[method] = wrapper;
  return remove;
  function wrapper(...args) {
    if (current === original && obj[method] === wrapper)
      remove();
    return current.apply(this, args);
  }
  function remove() {
    if (obj[method] === wrapper) {
      if (hadOwn)
        obj[method] = original;
      else
        delete obj[method];
    }
    if (current === original)
      return;
    current = original;
    Object.setPrototypeOf(wrapper, inherited || Function);
  }
}

// src/tracker.ts
var PositionTracker = class {
  constructor(plugin, store, settings) {
    /** Tracks whether a link was used to open the current file */
    this.linkUsed = false;
    /**
     * Counter for in-progress file transitions.
     * While > 0, position saves are blocked to prevent overwriting
     * stored positions with scroll=0 from newly-loading files.
     *
     * Incremented by: active-leaf-change (with 1s safety timeout)
     * Decremented by: restore completion (with 500ms settle delay)
     */
    this.filesOpening = 0;
    /** The last leaf we tracked, so we can save its position on switch-away */
    this.lastLeaf = null;
    this.plugin = plugin;
    this.store = store;
    this.settings = settings;
    this.layoutReady = plugin.app.workspace.layoutReady;
    this.saveDebounced = (0, import_obsidian2.debounce)(this.saveCurrentPosition.bind(this), 100, false);
    this.onScrollDebounced = (0, import_obsidian2.debounce)(this.handleScroll.bind(this), 100, false);
  }
  /**
   * Register all event listeners. Call once during plugin load.
   */
  register() {
    const app = this.plugin.app;
    if (this.settings.respectLinks) {
      this.plugin.register(
        around(import_obsidian2.Workspace.prototype, {
          openLinkText: (original) => {
            return async (linktext, sourcePath, newLeaf, openViewState) => {
              this.linkUsed = true;
              try {
                await original.call(
                  app.workspace,
                  linktext,
                  sourcePath,
                  newLeaf,
                  openViewState
                );
              } finally {
                this.linkUsed = false;
              }
            };
          }
        })
      );
    }
    this.plugin.registerEvent(
      app.workspace.on("file-open", () => {
        this.handleFileOpen();
      })
    );
    this.plugin.registerEvent(
      app.workspace.on("active-leaf-change", (newLeaf) => {
        var _a, _b;
        this.saveDebounced.cancel();
        if ((_b = (_a = this.lastLeaf) == null ? void 0 : _a.view) == null ? void 0 : _b.file) {
          this.saveLeafPosition(this.lastLeaf);
        }
        if ((newLeaf == null ? void 0 : newLeaf.view) && newLeaf.view.getViewType() === "markdown") {
          this.lastLeaf = newLeaf;
        } else {
          this.lastLeaf = null;
        }
        this.filesOpening++;
        window.setTimeout(() => {
          this.filesOpening = Math.max(0, this.filesOpening - 1);
        }, 1e3);
      })
    );
    this.plugin.registerEvent(
      app.vault.on("delete", (file) => {
        this.store.delete(file.path);
      })
    );
    this.plugin.registerEvent(
      app.vault.on("rename", (file, oldPath) => {
        this.store.rename(oldPath, file.path);
      })
    );
    app.workspace.onLayoutReady(() => this.handleLayoutReady());
    this.plugin.registerDomEvent(
      document,
      "scroll",
      (e) => this.onScrollDebounced(e),
      true
    );
    this.plugin.registerDomEvent(
      document,
      "touchend",
      () => {
        window.setTimeout(() => this.saveDebounced(), 300);
      },
      true
    );
    this.plugin.registerEvent(
      app.workspace.on("editor-change", () => this.saveDebounced())
    );
    this.plugin.registerInterval(
      window.setInterval(() => this.saveCurrentPosition(), 3e4)
    );
  }
  /**
   * Handle scroll events.
   */
  handleScroll() {
    if (!this.layoutReady || this.filesOpening > 0) return;
    this.saveCurrentPosition();
  }
  /**
   * Handle file open event. Restores saved position for the opened file.
   */
  handleFileOpen() {
    var _a, _b, _c;
    if (!this.layoutReady) {
      this.filesOpening = Math.max(0, this.filesOpening - 1);
      return;
    }
    const leaf = this.plugin.app.workspace.getMostRecentLeaf();
    if (this.settings.respectLinks) {
      const hasFlashing = (_b = (_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.containerEl) == null ? void 0 : _b.querySelector("span.is-flashing");
      if (hasFlashing || this.linkUsed) {
        this.filesOpening = Math.max(0, this.filesOpening - 1);
        return;
      }
    }
    if (!((_c = leaf == null ? void 0 : leaf.view) == null ? void 0 : _c.file)) {
      this.filesOpening = Math.max(0, this.filesOpening - 1);
      return;
    }
    this.restorePosition(leaf);
  }
  /**
   * Handle layout ready — restore all visible leaves on startup.
   */
  handleLayoutReady() {
    if (this.layoutReady) return;
    this.plugin.app.workspace.iterateRootLeaves((leaf) => {
      if (leaf.view instanceof import_obsidian2.FileView) {
        this.restorePosition(leaf);
      }
    });
    this.layoutReady = true;
  }
  /**
   * Save position for a specific leaf (used when switching away).
   */
  saveLeafPosition(leaf) {
    var _a;
    if (!((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.file)) return;
    const key = this.getFileKey(leaf.view);
    if (!key) return;
    const position = this.capturePosition(leaf.view);
    if (position) {
      this.store.set(key, position);
    }
  }
  /**
   * Save the current position of the active markdown view.
   */
  saveCurrentPosition() {
    if (!this.layoutReady || this.filesOpening > 0) return;
    const leaf = this.plugin.app.workspace.getMostRecentLeaf();
    if (!(leaf == null ? void 0 : leaf.view) || leaf.view.getViewType() !== "markdown") return;
    this.lastLeaf = leaf;
    const view = leaf.view;
    if (!view.file) return;
    const key = this.getFileKey(view);
    if (!key) return;
    const position = this.capturePosition(view);
    if (position) {
      this.store.set(key, position);
    }
  }
  /**
   * Capture the current cursor and scroll position from a view.
   */
  capturePosition(view) {
    const timestamp = Date.now();
    if (view.getViewType() === "markdown") {
      const mdView = view;
      if (mdView.getMode() === "source") {
        const cursor = mdView.editor.getCursor("head");
        const anchor = mdView.editor.getCursor("anchor");
        const scrollInfo = mdView.editor.getScrollInfo();
        const ephemeral = mdView.getEphemeralState();
        return {
          timestamp,
          scroll: ephemeral == null ? void 0 : ephemeral.scroll,
          scrollTop: scrollInfo == null ? void 0 : scrollInfo.top,
          cursor: {
            from: { line: anchor.line, ch: anchor.ch },
            to: { line: cursor.line, ch: cursor.ch }
          }
        };
      } else {
        const previewEl = view.containerEl.querySelector(".markdown-preview-view");
        if (previewEl) {
          return {
            timestamp,
            scrollTop: previewEl.scrollTop
          };
        }
      }
    }
    return null;
  }
  /**
   * Restore position for a leaf. Waits for the leaf to finish loading,
   * applies the position, then re-saves it to prevent overwrite during
   * the scroll settle period.
   */
  restorePosition(leaf) {
    var _a;
    if (!((_a = leaf == null ? void 0 : leaf.view) == null ? void 0 : _a.file)) {
      this.filesOpening = Math.max(0, this.filesOpening - 1);
      return;
    }
    const key = this.getFileKey(leaf.view);
    if (!key) {
      this.filesOpening = Math.max(0, this.filesOpening - 1);
      return;
    }
    const saved = this.store.get(key);
    if (!saved) {
      this.filesOpening = Math.max(0, this.filesOpening - 1);
      return;
    }
    let attempts = 0;
    const maxAttempts = 50;
    const tryRestore = () => {
      if (leaf.working && attempts++ < maxAttempts) {
        window.requestAnimationFrame(tryRestore);
        return;
      }
      window.setTimeout(() => {
        this.applyPosition(leaf.view, saved);
        window.setTimeout(() => {
          this.filesOpening = Math.max(0, this.filesOpening - 1);
        }, 500);
      }, this.settings.restoreDelay);
    };
    tryRestore();
  }
  /**
   * Apply a saved position to a view.
   *
   * Uses setEphemeralState({ scroll }) as the primary restore mechanism,
   * with editor.scrollTo(scrollTop) as fallback for mobile where
   * ephemeral state may not work reliably.
   */
  applyPosition(view, saved) {
    if (view.getViewType() === "markdown") {
      const mdView = view;
      if (mdView.getMode() === "source") {
        if (saved.cursor && this.settings.restoreCursor) {
          mdView.editor.setSelection(saved.cursor.from, saved.cursor.to);
        }
        if (saved.scroll !== void 0) {
          mdView.setEphemeralState({ scroll: saved.scroll });
        }
        if (saved.scrollTop !== void 0) {
          window.setTimeout(() => {
            var _a, _b;
            const currentTop = (_b = (_a = mdView.editor.getScrollInfo()) == null ? void 0 : _a.top) != null ? _b : 0;
            if (saved.scroll === void 0 || Math.abs(currentTop) < 5) {
              mdView.editor.scrollTo(0, saved.scrollTop);
            }
          }, 50);
        }
      } else {
        if (saved.scrollTop !== void 0) {
          const previewEl = view.containerEl.querySelector(
            ".markdown-preview-view"
          );
          if (previewEl) {
            previewEl.scrollTop = saved.scrollTop;
          }
        }
      }
    }
  }
  /**
   * Generate a unique key for a file view, incorporating split position
   * so the same file in different tabs gets independent tracking.
   */
  getFileKey(view) {
    if (!view.file) return null;
    const filePath = view.file.path;
    const splitId = this.getSplitId(view.leaf);
    return splitId ? `${filePath}#${splitId}` : filePath;
  }
  /**
   * Get a string ID representing the split position of a leaf.
   * Returns empty string for the primary (zero-indexed) leaf.
   */
  getSplitId(leaf) {
    var _a, _b, _c;
    if (!((_a = leaf == null ? void 0 : leaf.parent) == null ? void 0 : _a.parent)) return "";
    const path = [];
    let current = leaf.parent;
    while (current == null ? void 0 : current.parent) {
      const parent = current.parent;
      const idx = (_c = (_b = parent.children) == null ? void 0 : _b.indexOf(current)) != null ? _c : 0;
      path.unshift(idx);
      current = parent;
    }
    if (path.every((i) => i === 0)) return "";
    return path.join("-");
  }
};

// src/settings.ts
var import_obsidian3 = require("obsidian");
var SettingsTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian3.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian3.Setting(containerEl).setName("Restore cursor position").setDesc(
      "When enabled, restores your cursor position and scrolls to it. When disabled, only restores scroll position."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.restoreCursor).onChange(async (value) => {
        this.plugin.settings.restoreCursor = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Respect link navigation").setDesc(
      "Don't override position when navigating via heading or block links (e.g., [[note#heading]])."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.respectLinks).onChange(async (value) => {
        this.plugin.settings.respectLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Maximum stored positions").setDesc(
      "Limit how many note positions are remembered. Oldest are discarded first. Set to 0 for unlimited."
    ).addText(
      (text) => text.setPlaceholder("500").setValue(String(this.plugin.settings.maxPositions)).onChange(async (value) => {
        const num = parseInt(value, 10);
        if (!isNaN(num) && num >= 0) {
          this.plugin.settings.maxPositions = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Persist across restarts").setDesc(
      "Save positions to a file so they survive when Obsidian is closed and reopened."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.persistToDisk).onChange(async (value) => {
        this.plugin.settings.persistToDisk = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Restore delay").setDesc(
      "Delay in milliseconds before restoring position after opening a note. Increase if position isn't restoring correctly (e.g., with slow-loading plugins)."
    ).addSlider(
      (slider) => slider.setLimits(0, 500, 10).setValue(this.plugin.settings.restoreDelay).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.restoreDelay = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var RememberScrollPositionPlugin = class extends import_obsidian4.Plugin {
  async onload() {
    await this.loadSettings();
    this.store = new PositionStore(this, this.settings);
    await this.store.load();
    this.tracker = new PositionTracker(this, this.store, this.settings);
    this.tracker.register();
    this.addSettingTab(new SettingsTab(this.app, this));
  }
  onunload() {
    var _a;
    void ((_a = this.store) == null ? void 0 : _a.flush());
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      { filePath: this.defaultFilePath() },
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  defaultFilePath() {
    return `${this.app.vault.configDir}/plugins/remember-scroll-position/positions.json`;
  }
};
