gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - '#89b4fa'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89b4fa'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  authorColors:
    '*': '#b4befe'
keybinding:
  files:
    openFile: '<disabled>'
  universal:
    openRecentRepos: '<disabled>'
customCommands:
  - key: 'o'
    context: 'files'
    command: 'nvim {{.SelectedFile.Name}}'
    output: terminal
  - key: 'o'
    context: 'commits'
    command: 'echo "Commit: {{.SelectedLocalCommit.Sha}}" && nvim'
    output: terminal
  - key: 'o'
    context: 'commitFiles'
    command: 'nvim {{.SelectedCommitFile.Name}}'
    output: terminal
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
