"use strict";var E=Object.create;var u=Object.defineProperty;var x=Object.getOwnPropertyDescriptor;var T=Object.getOwnPropertyNames;var _=Object.getPrototypeOf,I=Object.prototype.hasOwnProperty;var N=(t,e)=>{for(var n in e)u(t,n,{get:e[n],enumerable:!0})},d=(t,e,n,o)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of T(e))!I.call(t,r)&&r!==n&&u(t,r,{get:()=>e[r],enumerable:!(o=x(e,r))||o.enumerable});return t};var O=(t,e,n)=>(n=t!=null?E(_(t)):{},d(e||!t||!t.__esModule?u(n,"default",{value:t,enumerable:!0}):n,t)),b=t=>d(u({},"__esModule",{value:!0}),t);var v={};N(v,{default:()=>D});module.exports=b(v);var s=require("@raycast/api");var h=O(require("node:process"),1),S=require("node:util"),l=require("node:child_process"),P=(0,S.promisify)(l.execFile);async function c(t,{humanReadableOutput:e=!0,signal:n}={}){if(h.default.platform!=="darwin")throw new Error("macOS only");let o=e?[]:["-ss"],r={};n&&(r.signal=n);let{stdout:a}=await P("osascript",["-e",t,o],r);return a.trim()}var p=60,f=24*p,A=7*f;function g(t){let e=Math.max(0,Math.floor(t));if(e===0)return"less than a minute";let n=e,o=Math.floor(n/A);n%=A;let r=Math.floor(n/f);n%=f;let a=Math.floor(n/p),m=n%p,i=[];if(o&&i.push(`${o} week${o===1?"":"s"}`),r&&i.push(`${r} day${r===1?"":"s"}`),a&&i.push(`${a} hour${a===1?"":"s"}`),m&&i.push(`${m} minute${m===1?"":"s"}`),i.length===0)return"less than a minute";if(i.length===1){let[$]=i;return $}return i.length===2?`${i[0]} and ${i[1]}`:`${i.slice(0,-1).join(", ")}, and ${i[i.length-1]}`}var w=require("@raycast/api");async function y(){return!!(await(0,w.getApplications)()).find(n=>n.bundleId==="com.if.Amphetamine")}var M="https://apps.apple.com/br/app/amphetamine/id937984704";function R(t,e){return e==="hours"?t*60:t}async function D(t){let e=t?.duration,n=t?.interval,o=new s.Toast({title:"Starting a new session",style:s.Toast.Style.Animated});return o.show(),await y()?await c(`
    tell application "Amphetamine"
    		return session is active
    end tell
  `)==="true"?(o.title="A session is already running",o.style=s.Toast.Style.Failure,!1):(await c(`
    tell application "Amphetamine"
        start new session ${e?`with options {duration: ${e}, interval: ${n}, displaySleepAllowed: false}`:""}
    end tell
  `),await(0,s.showHUD)(e&&n?`New session started: ${g(R(e,n))}`:"New default session started"),!0):(o.title="Amphetamine is no installed",o.message="Press Command + D to download",o.primaryAction={title:"Download",shortcut:{modifiers:["cmd"],key:"d"},onAction:async()=>await(0,s.open)(M)},o.style=s.Toast.Style.Failure,!1)}
